#!/usr/bin/env bash
# 0. World wide web

if [$# == 1]
then
    all_subdomains()
elif [ $# == 2 ]
then
    domain=$2
    domain="${domain}." 
    domain="${domain}${1}"
    RECORD_TYPE=$(dig $domain | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
    DESTINATION=$(dig $domain | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
    echo 'The subdomain' $2 'is a' $RECORD_TYPE 'record and points to' $DESTINATION
fi
