#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [[ $# -ne 4 ]]
then 
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit
fi
# scp fileName/Path_to_file 
# username_of_remote_host@IP(remote_host):the_directory_to_be_cobied_on(PATH_TO_SSH_KEY)
scp -o StrictHostKeyChecking=no  -i "$4" "$1" "$3"@"$2":"$1"
#scp -i PATH_TO_SSH_KEY File_Name/PATH_TO_FILE  USERNAME@IP:File_Name/PATH_TO_FILE
#./0-transfer_file 0-body_size.sh 100.25.153.226 ubuntu ~/.ssh/id_rsa
#ssh ubuntu@100.25.153.226 -i ~/.ssh/id_rsa