#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [[ $# -ne 4 ]]
then 
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit
fi
# scp fileName/Path_to_file 
# username_of_remote_host@IP(remote_host):the_directory_to_be_cobied_on(PATH_TO_SSH_KEY)
scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/.
