#!/usr/bin/env bash
# Install nginx web server

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Change the default webpage
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/index.html

#start nginx
sudo service nginx start
