#!/usr/bin/env bash
# Install nginx web server

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

#start nginx
sudo service nginx start

# Change the default webpage
sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
