#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Change the default webpage
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/index.html

sudo chmod o+w /etc/nginx/sites-available/default

sudo sed -i "s/_;/_;\n\tlocation = \/redirect_me {\n\t\treturn 301  https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default;

#start nginx
sudo service nginx start

#location = /redirect_me {
# return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#}
