#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

#start nginx
sudo service nginx start

sed -i "s/_;/_;location = /redirect_me {\nreturn 301  https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/" /etc/nginx/sites-available/default;

service nginx restart

#location = /redirect_me {
# return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#}
