#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Change the default webpage
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/index.html

sudo chmod o+w /etc/nginx/sites-available/default

# Change config to permenant moved 301
sudo sed -i "s/_;/_;\n\tlocation = \/redirect_me {\n\t\treturn 301  https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}/" /etc/nginx/sites-available/default;

#location = /redirect_me {
# return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#}
sudo mkdir /var/www/errors

# Configure to have a custom 404 page

echo -e "Ceci n'est pas une page\n" > 404.html
sudo mv  404.html /var/www/errors/404.html

sudo sed -i "s/_;/_;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot  \/var\/www\/errors;\n\tinternal;\n\t}/" /etc/nginx/sites-available/default; 

#start nginx
sudo service nginx start

#error_page 404 /404.html;
#location = /404.html {
    #EDIT this line to make it match the folder where there is your errors page
    #Dont forget to create 404.html in this folder
#    root  /var/www/errors/;
#  }
