#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get update
sudo apt-get -y install nginx

sudo chmod o+w /etc/nginx/sites-available/default

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html

sudo mkdir -p /var/www/errors
sudo touch /var/www/errors/404.html
sudo echo "Ceci n'est pas une page" > /var/www/errors/404.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;

        root /var/www/html;

        index index.html;

        server_name _;

        location = /redirect_me {
                return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;

        location = /404.html {
                root  /var/www/errors;
                internal;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx start
