#!/usr/bin/env bash
# Install your load balancer on lb-01 server.

new_config=\
"
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web01 100.25.153.226:80 check
        server web02 3.83.253.145:80 check
"

sudo chmod o+w /etc/haproxy/haproxy.cfg

echo "$new_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#Make sure that HAproxy can be managed via an init script:
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
