#!/usr/bin/env bash
# 0. Nginx likes port 80
sudo apt-get update
sudo apt-get -y install nginx
# Remove the default Nginx Config file
sudo rm /etc/nginx/sites-enabled/default
# it configs Nginx to listen on port 80 for active IPv4 IPs
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restarts Nginx
sudo service nginx restart
