#!/usr/bin/env bash
# Using task #0 Make it sweet and short service must say that nginx is not running
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -f nginx
