#!/usr/bin/env bash
#A Bash script that displays Best School 10 times using while
#but for the 9th iteration, displays
#Best School and then Hi on a new line.
until
i=0
until [ $i -eq 10 ]
do
    echo "Best School"
    ((i++))
done
