#!/usr/bin/env bash
#A Bash script that displays Best School 10 times using while
#but for the 9th iteration, displays
#Best School and then Hi on a new line.
i=1
while [ $i -lt 11 ]
do
    echo "Best School"
    if [ $i == 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
