#!/usr/bin/env bash
#script that displays the content of the current directory use for loop
#In a list format
#Where only the part of the name after the first dash is displayed

for i in *
do
    echo $i | sed 's/^[0-9]*-//'
done
